#!/usr/bin/env python3

import sys
n = int(sys.argv[1])

states = { (n,0): 1 }
depth = 0

while len(states):
    newstates = {}
    totalw = 0
    totalh = 0

    for s in states.keys():
        totalw += s[0]
        totalh += s[1]
        
        if s[0] > 0:         # wholes
            ns = (s[0] - 1, s[1] + 1)
            if ns not in newstates:
                newstates[ns] = 1
        if s[1] > 0:        # halves
            ns = (s[0], s[1] - 1)
            if ns not in newstates:
                newstates[ns] = 1
      
    # average likelihood of drawing a half across all states at this depth
    ph = 1 if totalw==0 else totalh / (totalh + totalw) * 100

    print(f'{depth}, {int(ph)}')

    states = newstates
    depth += 1
