#!/usr/bin/env python

'''
Make exhaustive graph for N pills. See pill-bottle.

Produces:
   - DOT language on stdout
   - errors on stderr

Example usage:
    $ make-graph N > foo.gv
    $ dot -Tpng foo.gv > foo.png
    $ view foo.png
'''

from common import Common
import sys

def print_graph():
    print("digraph Pills {")
    print('label="%d edges for N=%d"' % (len(c.edges), N))
    for e in c.edges:
        print(e)
    print("}")

N = int(sys.argv[1])
c = Common()

c.draw_pill(N, 0)
print_graph()
